---
- hosts: all
  gather_facts: no
  tasks:
  - name: Creating the download folder...
    win_file:
      path: "{{ dir_base }}\\{{ name_folder }}"
      state: directory

  - name: Downloading the files...
    win_get_url:
      url: "{{ item }}"
      dest: "{{ dir_base }}\\{{ name_folder }}"
      force: no
    loop: "{{ urls }}"

  - name: Copying files on network...
    win_copy:
      src: "{{ dir_base }}\\{{ name_folder }}"
      dest: "\\\\{{ item }}\\c$\\DUWF\\PacotesQualidade\\"
      remote_src: yes
    #become: yes
    #become_method: runas
    #become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    #vars:
    #  ansible_become_user: '{{lookup (env, "ansible_user" }}'
    #  ansible_become_pass: '{{lookup (env, "ansible_password" }}'
    loop: "{{ servers_copy }}"
    when: servers_copy != ['']
