---
- hosts: all
  gather_facts: false
  tasks:
  - name: Install PSCX
    win_psmodule:
      name: Pscx
      state: present
      allow_clobber: yes
  - name: Unzip a package script
    win_unzip:
      src: C:\DUWF\PacotesQualidade\test\DealerNetRelatorio.gz
      dest: C:\DUWF\PacotesQualidade\test-archive
      recurse: yes